#!/usr/sbin/nft -f
flush ruleset
define TOR_UID = 109
define TRANS_PORT = 9040
define DNS_PORT = 5353
table inet filter {
  chain input { type filter hook input priority 0; policy drop; iif "lo" accept; ct state established,related accept; }
  chain forward { type filter hook forward priority 0; policy drop; }
  chain output { type filter hook output priority 0; policy drop; oif "lo" accept; ct state established,related accept; meta skuid $TOR_UID accept; }
}
table ip nat {
  chain output {
    type nat hook output priority -100;
    meta skuid $TOR_UID return
    ip daddr 127.0.0.0/8 return
    udp dport 53 redirect to :$DNS_PORT
    tcp dport 53 redirect to :$DNS_PORT
    ip protocol tcp redirect to :$TRANS_PORT
  }
}
